### PR TITLE
Update sebastian.md

### PR DESCRIPTION
**Pull request by SFRL**
Update profile

### CODE REVIEW

**Comment by Nagasaki45** [comment]
Thanks for the PR @SFRL! Note that not everyone on MAT is comfortable with git, so the main workflow is going to be giving everyone write access to this repo and then students and staff will be able to edit content using the built in online editor here on github. Adding you to the @QMUL-MAT/website-editors teams so you can do the same, but feel free to send PRs instead if you prefer (at least while I'm still in charge :-)).

**Comment by SFRL** [comment]
Hi Tom,

I tried to update my profile again and it appears that I still don’t have the permission to change/add files despite being on the “Website Editors” team. I could of course send another “pull request”, but I guess that’s not the workflow that you had in mind? Maybe I am doing something wrong, but I really just followed your description step by step.

Best,
Sebastian

**Comment by Nagasaki45** [comment]
Thanks a lot for that! This is the exact reason I was waiting before sending the email to everyone on MAT: testing the workflow. I forgot to add write access to the repo for the @QMUL-MAT/website-editors team. Should be sorted now. Can you please try again?

**Comment by SFRL** [comment]
Seems to be working now, at least I was able to commit. I’ll let you know when/if the changes appear on the page. 

Coincidently, I started learning Gatsby.js a few days ago to use for my own webpage. Seems like I’m accidentally training to become your successor :)

Best,
Sebastian

**Comment by Nagasaki45** [comment]
> Coincidently, I started learning Gatsby.js a few days ago to use for my own webpage. Seems like I’m accidentally training to become your successor :)

Haha! Be careful what you wish for :-)

I can see your updates now as well. Thanks for contributing ;-)

**Pull request merged**
